project:
  type: website
  output-dir: docs

website:
  title: "Lukas Lescano"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resume-CV.qmd
        text: Synopsis
      - portfolio.qmd
      - coursework.qmd
  page-footer:
    background: dark
    left: Copyright 2025, Lukas Lescano
    right: This website is built with [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/samanthacsik/samanthacsik.github.io){target=_blank}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank}, and [Quarto](https://quarto.org/){target=_blank}

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    page-layout: full

editor: visual