project:
  type: website
  output-dir: docs

website:
  title: "Lukas Lescano"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resume-CV.qmd
        text: Synopsis
      - portfolio.qmd
      - coursework.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    page-layout: full

editor: visual